DROP DATABASE IF EXISTS `UnirDB`;
CREATE DATABASE `UnirDB`;

USE `UnirDB`

DROP TABLE IF EXISTS `Comercial`;

CREATE TABLE `Comercial`(
    `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NOMBRE` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `APELLIDO1` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `APELLIDO2` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `COMISION` DECIMAL(10,2) UNSIGNED NOT NULL,
    CONSTRAINT `comercial_repit_pk` UNIQUE (`NOMBRE`, `APELLIDO1`, `APELLIDO2`)
)DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `Cliente`;

CREATE TABLE `Cliente`(
    `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NOMBRE` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `APELLIDO1` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `APELLIDO2` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `CIUDAD` VARCHAR(100) NOT NULL,
    `CATEGORIA` INT UNSIGNED DEFAULT NULL,
    CONSTRAINT `cliente_repit_pk` UNIQUE(`NOMBRE`, `APELLIDO1`, `APELLIDO2`, `CIUDAD`)
)DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `Pedidos`;

CREATE TABLE `Pedidos`(
    `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `TOTAL` DECIMAL(10,2) UNSIGNED NOT NULL,
    `FECHA` DATE NOT NULL,
    `ID_CLIENTE` INT UNSIGNED NOT NULL,
    `ID_COMERCIAL` INT UNSIGNED NOT NULL,
    CONSTRAINT `cliente_fk` FOREIGN KEY(`ID_CLIENTE`) REFERENCES `Cliente`(`ID`),
    CONSTRAINT `comercial_fk` FOREIGN KEY(`ID_COMERCIAL`) REFERENCES `Comercial`(`ID`)
)DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
